[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]